### ISSUE TITLE
Digitalocean tables

### ISSUE THREAD

**Issue by DeolTito** [cloudquery/cq-provider-digitalocean#98]
### Describe the Bug
I've installed Cloudquery on my machine and fetched the tables from digitaloceans. However, I'm not able to view 2fa or MFA details of my account from those tables. Can you please let me know tables on which I can view those details?

### Expected Behavior

Using the query, I should be able to view the 2fa enabled on my account.

**Comment by bbernays** [comment]
Hi @DeolTito - I have looked through the [documentation](https://docs.digitalocean.com/reference/api/api-reference/#operation/get_user_information) for Digital Ocean's API and cannot find any mention of user MFA status. We can only ingest data that is available via the API. If you are aware of an API that can specify the MFA status for a digital ocean user we would be happy to add support for it in CloudQuery

**Comment by bbernays** [comment]
Feel free to re-open or create a new issue if you have any other questions or concerns
